config/routes.rb
Rails.application.routes.draw do
  resources :menu_items do
    resources :orders
  end
  resources :sections

  get 'menu' => 'menu#index'
  get 'contact_us' => 'welcome#contact_us'

  root 'welcome#index'

end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  belongs_to :section
  has_many :orders, dependent: :destroy

  include ActionView::Helpers::NumberHelper

  IMAGE_BASE_URL = "http://loremflickr.com/320/240/"

  def image_url_or_default
   	if image_url.present?
   	  image_url
    else
      "#{IMAGE_BASE_URL}#{CGI.escape name}"
   	end
  end

  def formated_price
    "#{number_with_precision(price, precision: 0, delimiter: ',')} VND"
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :menu_item

  validates :menu_item, :name, presence: true
end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :menu_items, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  add_flash_types :success
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def index
    @sections = Section.all
    params[:section_id] ||= Section.first.try(:id)
    section = Section.find_or_initialize_by(id: params[:section_id])
    @sort = params[:sort] || "alphabetical"
    @menu_items = case @sort
                  when "price_low_to_high" then section.menu_items.order(:price)
                  when "price_high_to_low" then section.menu_items.order(price: :desc )
                  else section.menu_items.order(:name)
                  end
    @section_id = section.id
  end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  before_action :set_menu_item, only: [:show, :edit, :update, :destroy]

  # GET /menu_items
  # GET /menu_items.json
  def index
    @menu_items = MenuItem.all
  end

  # GET /menu_items/1
  # GET /menu_items/1.json
  def show
  end

  # GET /menu_items/new
  def new
    @menu_item = MenuItem.new
    @sections = Section.all
  end

  # GET /menu_items/1/edit
  def edit
    @sections = Section.all
  end

  # POST /menu_items
  # POST /menu_items.json
  def create
    @menu_item = MenuItem.new(menu_item_params)

    respond_to do |format|
      if @menu_item.save
        format.html { redirect_to @menu_item, notice: 'Menu item was successfully created.' }
        format.json { render :show, status: :created, location: @menu_item }
      else
        format.html { render :new }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menu_items/1
  # PATCH/PUT /menu_items/1.json
  def update
    respond_to do |format|
      if @menu_item.update(menu_item_params)
        format.html { redirect_to @menu_item, notice: 'Menu item was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu_item }
      else
        format.html { render :edit }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_items/1
  # DELETE /menu_items/1.json
  def destroy
    @menu_item.destroy
    respond_to do |format|
      format.html { redirect_to menu_items_url, notice: 'Menu item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu_item
      @menu_item = MenuItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_item_params
      params.require(:menu_item).permit(:name, :description, :price, :section_id, :image_url)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @menu_item = MenuItem.find params[:menu_item_id]
  end

  def create
    @menu_item = MenuItem.find params[:menu_item_id]

    @order = Order.new(order_params)
    @order.menu_item = @menu_item

    if @order.save
      redirect_to menu_path, success: ORDER_SUCCESSFULLY_MESSAGE
    else
      flash.now[:error] = "Error: #{@order.errors.full_messages.to_sentence}"
      render 'new'
    end
  end

  private
  def order_params
    params.require(:order).permit(:name, :phone, :address)
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def contact_us
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_class_for(flash_type)
    {
        success: 'alert-success',
        error: 'alert-danger',
        alert: 'alert-warning',
        notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <% puts "AAAA" %>
  <% puts type %>
  <% puts message %>
  <div class="alert <%= alert_class_for(type) %> alert-dismissible fade in">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- <title>CheetahRestaurant</title> -->
  <title><%= RESTAURANT_NAME %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
  	<nav class="navbar navbar-dark bg-inverse" >
  	  <%= link_to RESTAURANT_NAME, root_path, class: 'navbar-brand' %>
	  <ul class="nav navbar-nav pull-xs-right">
	    <li class="nav-item active">
	      <a class="nav-link" href="#">Orders(0) <span class="sr-only">(current)</span></a>
	    </li>
	    <li class="nav-item">
	      <a class="nav-link" href="#">Items</a>
	    </li>
	  </ul>
	</nav>
	<br/>

  <%= render partial: 'layouts/flash_messages', flash: flash %>

  <%= yield %>

  </div>
</body>
</html>

app/views/menu/index.html.erb
<h1><%= RESTAURANT_NAME %> Menu</h1>

<ul class="nav nav-tabs">
  <% @sections.each do |section| %>
    <li class="nav-item">
      <% class_name = section.id == @section_id ? 'nav-link active' : 'nav-link' %>
      <%= link_to section.name, menu_path(section_id: section.id), class: class_name %>
    </li>
  <% end %> 
</ul>
<br/>

<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdown-sort" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <%= @sort.titlecase %>
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdown-sort">
    <%= link_to 'Alphabetical', menu_path(section: @section_id, sort: 'alphabetical'), class: 'dropdown-item'  %>
    <%= link_to 'Price Low To High', menu_path(section: @section_id, sort: 'price_low_to_high'), class: 'dropdown-item'  %>
    <%= link_to 'Price High To Low', menu_path(section: @section_id, sort: 'price_high_to_low'), class: 'dropdown-item'  %>
  </div>
</div>
<br/>

<% @menu_items.in_groups_of(3) do |group| %>
  <div class="row">
  	<% group.compact.each do |item| %>
      <div class="col-sm-4">
    	  <div class="card">
    	  	<p style="text-align: center">
            <%= image_tag item.image_url_or_default, alt: item.name, style: 'width: 100%', class: 'card-img-top' %>
          </p>
    	    <div class="card-block">
    	      <h4 class="card-title">
              <%= link_to item.name, item %>
              <span class="label label-default"><%= item.orders.size %></span>
            </h4>
    	      <p class="card-text"><%= item.description %></p>
            <div class="row">
              <div class="col-md-6">
                <span class="label label-info"><%= item.formated_price %></span>
              </div>
              <div class="col-md-offset-6 text-xs-right">
                <%= link_to "Order", new_menu_item_order_path(item.id), class: "btn btn-success pull-right"  %>
              </div>
            </div>
    	    </div>
    	  </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/menu_items/_form.html.erb
<%= form_for(@menu_item) do |f| %>
  <% if @menu_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu_item.errors.count, "error") %> prohibited this menu_item from being saved:</h2>

      <ul>
      <% @menu_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group row">
    <%= f.label :name, class: 'col-sm-2 form-control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :description, class: 'col-sm-2 form-control-label' %>
    <div class="col-sm-10">
      <%= f.text_area :description, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :price, class: 'col-sm-2 form-control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :price, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 form-control-label">Section</label>
    <div class="col-sm-10">
      <fieldset class="form-group">
        <select class="form-control" name="menu_item[section_id]" id="menu_item_section_id">
          <% selected_section_id = @menu_item.section.id || @sections.first.id %>
          <% @sections.each do |section| %>
            <option value="<%= section.id %>" <%= section.id == selected_section_id ? 'selected' : '' %>>
              <%= section.name %>
            </option>
          <% end %>
        </select>
      </fieldset>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :image_url, class: 'col-sm-2 form-control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :image_url, class: 'form-control' %>
    </div>
  </div>
  
  <div class="form-group row">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-primary">Create</button>
    </div>
  </div>
<% end %>

app/views/menu_items/edit.html.erb
<h1>Editing Menu Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu_item %> |
<%= link_to 'Back', menu_items_path %>

app/views/menu_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Menu Items</h1>

<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Section</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menu_items.each do |menu_item| %>
      <tr>
        <td><%= menu_item.name %></td>
        <td><%= menu_item.description %></td>
        <td><%= menu_item.price %></td>
        <td><%= menu_item.section.name %></td>
        <td><%= menu_item.image_url %></td>
        <td><%= link_to 'Show', menu_item %></td>
        <td><%= link_to 'Edit', edit_menu_item_path(menu_item) %></td>
        <td><%= link_to 'Destroy', menu_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu item', new_menu_item_path, class: 'btn btn-primary-outline' %>

app/views/menu_items/new.html.erb
<h1>New Menu Item</h1>

<%= render 'form' %>

<%= link_to 'Back', menu_items_path %>

app/views/menu_items/show.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
  <div class="row">
    <div class="col-sm-6">
      <%= image_tag @menu_item.image_url_or_default, alt: @menu_item.name, style: 'width: 100%' %>
    </div>
    <div class="col-sm-6">
      <h2>
        <%= @menu_item.name %>
        <span class="label label-default"><%= @menu_item.orders.size %></span>
      </h2>
      <table width="100%">
        <tr>
          <td class="title-right">Description</td>
          <td><%= @menu_item.description %></td>
        </tr>
        <tr>
          <td class="title-right">Section</td>
          <td><%= @menu_item.section.name %></td>
        </tr>
        <tr>
          <td class="title-right">Price</td>
          <td><span class="label label-info"><%= @menu_item.formated_price %></span></td>
        </tr>
      </table>
      <br/>
      <%= link_to "Order", new_menu_item_order_path(@menu_item.id), class: "btn btn-success"  %>
    </div>
  </div>
</div>

app/views/orders/new.html.erb
<h1>
  <small>Order for</small> <%= @menu_item.name %>
</h1>

<%= form_for [@menu_item, Order.new] do |f| %>
  <div class="row">
    <div class="col-sm-4">
      <div class="form-group row">
        <%= f.label :name, class: 'col-sm-2 form-control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :name, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :phone, class: 'col-sm-2 form-control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :phone, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :address, class: 'col-sm-2 form-control-label' %>
        <div class="col-sm-10">
          <%= f.text_area :address, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit "Submit Order", class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
<% end %>  

app/views/sections/_form.html.erb
<%= form_for(@section) do |f| %>
  <% if @section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% @section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-inline">
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
  </div>
<% end %>

app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form' %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

app/views/sections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sections</h1>

<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.name %></td>
        <td><%= link_to 'Show', section %></td>
        <td><%= link_to 'Edit', edit_section_path(section) %></td>
        <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Section', new_section_path, class: 'btn btn-primary-outline' %>

app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'form' %>
<br/>
<%= link_to 'Back', sections_path %>

app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @section.name %>
</p>

<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>

app/views/welcome/contact_us.html.erb
<h1>Contact Us</h1>

<div class="row">
  <div class="col-sm-4">
  	<address>
  	  <b><%= RESTAURANT_NAME %></b><br/>
  	  44 Lý Tự Trọng, Bến Nghé, 1, Hồ Chí Minh, Việt Nam
  	</address>
  </div>
  <div class="col-sm-8">
  	<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.4485262701596!2d106.69803441458829!3d10.776918562131975!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752f47f4bf195d%3A0x675567b1b6a70538!2sNh%C3%A0+H%C3%A0ng+Le+Fenetre+Soleli!5e0!3m2!1sen!2s!4v1452572504397" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron" style="background-color: #C2C2C2">
  <div class="row">
    <div class="col-sm-7">
      <h3 class="display-5">Welcome to</h3>
      <h1 class="display-3">Cheetah Restaurant</h1>
      <p class="lead">
        <div class="btn-group" role="group" aria-label="Basic example">
      	  <%= link_to "Menu", menu_path, class: 'btn btn-secondary' %>
      	  <%= link_to "Contact Us", contact_us_path, class: 'btn btn-secondary' %>
        </div>
      </p>
    </div>
    <div class="col-sm-5">
      <%= image_tag "http://media-cdn.tripadvisor.com/media/photo-s/06/42/b6/58/la-fenetre-soleil.jpg", style: 'width: 100%' %>
    </div>
  </div>
</div>